### ISSUE TITLE
multiple controller specs & missing "require 'spec_helper'"

### ISSUE THREAD

**Issue by asherkory** [learn-co-students/sinatra-fwitter-group-project-v-000#53]
There are two almost entirely identical controller specs. It looks like "controller_spec.rb" may be newer than "application_controller_spec.rb" since it has two more tests. Might want to remove the other one.

Also, models/user_spec.rb is missing a "require 'spec_helper'" at the top.

**Comment by bhollan** [comment]
I think this can be closed now @aturkewi .  The `spec/controller_spec.rb` file doesn't seem to be there any longer.

**Comment by aturkewi** [comment]
Looks like this one was already solved then :)
